package initialize

import (
  "bufio"
  "errors"
  "os"

  "github.com/craigmonson/colonize/config"
  "github.com/craigmonson/colonize/log"
)



func Run(c *config.ColonizeConfig, l log.Logger) error {

  scan := bufio.NewScanner(os.Stdin)
  l.Log("Initializing a new Colonize project")

  // templates_dir
  l.Print("Enter 'templates_dir' [env]: ")
  c.Templates_Dir = scan_with_default(scan, "env")

  // environments_dir
  l.Print("Enter 'environments_dir' [env]: ")
  c.Environments_Dir = scan_with_default(scan, "env")

  // base_environment_ext
  l.Print("Enter 'base_environment_ext' [default]: ")
  c.Base_Environment_Ext = scan_with_default(scan, "default")

  // autogenerate_comment
  c.Autogenerate_Comment = "This file generated by coloinze"

  // combined_vals_file
  l.Print("Enter 'combined_vals_file' [_combined.tfvars]: ")
  c.Combined_Vals_File = scan_with_default(scan, "_combined.tfvars")

  // combined_vars_file
  l.Print("Enter 'combined_vars_file' [_combined_variables.tf]: ")
  c.Combined_Vars_File = scan_with_default(scan, "_combined_variables.tf")

  // combined_derived_vals_file
  l.Print("Enter 'combined_derived_vals_file' [_combined_derived.tfvars]: ")
  c.Combined_Derived_Vals_File = scan_with_default(scan, "_combined_derived.tfvars")

  // combined_derived_vars_file
  l.Print("Enter 'combined_derived_vars_file' [_combined_derived.tf]: ")
  c.Combined_Derived_Vars_File = scan_with_default(scan, "_combined_derived.tf")

  // combined_tf_File
  l.Print("Enter 'combined_tf_file' [_combined.tf]: ")
  c.Combined_Tf_File = scan_with_default(scan, "_combined.tf")

  // combined_remote_config_file
  l.Print("Enter 'combined_remote_config_file' [_remote_setup.sh]: ")
  c.Combined_Remote_Config_File = scan_with_default(scan, "_remote_setup.sh")

  // remote_config_file
  l.Print("Enter 'remote_config_file' [remote_setup.sh]: ")
  c.Remote_Config_File = scan_with_default(scan, "remote_setup.sh")

  // derived_file
  l.Print("Enter 'derived_file' [derived.tfvars]: ")
  c.Derived_File = scan_with_default(scan, "derived.tfvars")

  // vals_file_env_post_string
  l.Print("Enter 'vals_file_env_post_string' [.tfvars]: ")
  c.Vals_File_Env_Post_String = scan_with_default(scan, ".tfvars")

  // print configuration details
  print_config(c,l)

  // Confirm initialization
  accept := ""
  l.Log("\n")
  for accept == "" {
    l.Print("Please enter [y] to accept this configuration or [n] to cancel: ")
    scan.Scan()
    accept = scan.Text()
  }

  if accept != "y" {
    return errors.New("Colonize initialization cancelled by user")
  }

  err := os.Mkdir(c.Templates_Dir,0644)
  if err != nil {
    return err
  }

  if c.Templates_Dir != c.Environments_Dir {
    err = os.Mkdir(c.Environments_Dir,0644)
    if err != nil {
      return err
    }
  }


  //
  // TODO: Generate remote config file??
  //

  return c.WriteToFile(".colonize.yaml")
}

func scan_with_default(scan *bufio.Scanner, deflt string) string {

  scan.Scan()
  value := scan.Text()
  if value == "" {
    return deflt
  }

  return value
}

func print_config(c *config.ColonizeConfig, l log.Logger) {
  l.Log("\n\nInitializing Colonize using the following config:")
  l.Log("templates_dir               => " + c.Templates_Dir)
  l.Log("environments_dir            => " + c.Environments_Dir)
  l.Log("base_environment_ext        => " + c.Base_Environment_Ext)
  l.Log("combined_vals_file          => " + c.Combined_Vals_File)
  l.Log("combined_vars_file          => " + c.Combined_Vars_File)
  l.Log("combined_derived_vals_file  => " + c.Combined_Derived_Vars_File)
  l.Log("combined_derived_vars_file  => " + c.Combined_Derived_Vals_File)
  l.Log("combined_tf_file            => " + c.Combined_Tf_File)
  l.Log("combined_remote_config_file => " + c.Combined_Remote_Config_File)
  l.Log("remote_config_file          => " + c.Remote_Config_File)
  l.Log("derived_file                => " + c.Derived_File)
  l.Log("vals_file_env_post_string   => " + c.Vals_File_Env_Post_String)
}
